# Python to Linux Web App on Azure
# Build your Python project and deploy it to Azure as a Linux Web App.

trigger:
- main

variables:
  # Azure Resource Manager connection
  azureServiceConnectionId: 'abaa671b-36dd-4136-b05d-ecfb61eaf3c1'

  # Web app name
  webAppName: 'Relecloud-2526'

  # Environment name
  environmentName: 'Relecloud-2526'

  # Project root folder. Folder que contiene manage.py
  projectRoot: $(System.DefaultWorkingDirectory)

  # Ruta a Python en el agente self-hosted
  pythonPath: '/usr/bin/python3'

stages:
- stage: Build
  displayName: 'Build stage'
  jobs:
  - job: BuildJob
    displayName: 'BuildJob'
    pool:
      name: 'IS2-Practica2'   # agente self-hosted
    steps:
    - script: |
        $(pythonPath) --version
      displayName: 'Check Python version'

    - script: |
        $(pythonPath) -m venv antenv
        source antenv/bin/activate
        python -m pip install --upgrade pip
        pip install setuptools
        pip install -r requirements.txt
      workingDirectory: $(projectRoot)
      displayName: 'Install requirements'

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(projectRoot)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    - upload: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      displayName: 'Upload package'
      artifact: drop

- stage: Deploy
  displayName: 'Deploy Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    displayName: 'DeploymentJob'
    pool:
      name: 'IS2-Practica2'   # mismo agente
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App : Relecloud-2526'
            inputs:
              appType: webApp
              azureSubscription:
              appName: $(webAppName)
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
