
trigger:
- main

variables:
  # Azure Resource Manager connection created during pipeline creation
  azureServiceConnectionId: 'Azure for Students(033e26f8-876d-4414-b6bc-673accd6b842)'


  # Web app name
  webAppName: 'Relecloud-2526'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  # Environment name
  environmentName: 'Relecloud-2526'

  # Project root folder. Point to the folder containing manage.py file.
  # Ruta correcta donde est√° manage.py y requirements.txt
  projectRoot: '$(Build.SourcesDirectory)\django\django'

  #pythonVersion: '3.12'
  pythonPath: '/usr/bin/python3'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool:
      name: 'IS2-Practica2'
    steps:
    # - task: UsePythonVersion@0
    #   inputs:
    #     versionSpec: '$(pythonVersion)'
    #   displayName: 'Use Python $(pythonVersion)'

    - script: |
        echo Cambiando a la carpeta del proyecto:
        cd
        dir

        echo Creando entorno virtual...
        python -m venv antenv

        echo Activando entorno virtual...
        call antenv\Scripts\activate

        echo Actualizando pip y setuptools...
        python -m pip install --upgrade pip
        pip install --upgrade setuptools

        echo Instalando dependencias...
        pip install -r requirements.txt
      workingDirectory: '$(projectRoot)'
      displayName: 'Install requirements'

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(projectRoot)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      displayName: 'Upload package'
      artifact: drop

- stage: Deploy
  displayName: 'Deploy Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    pool: 
      name: 'IS2-Practica2'
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:

          # - task: UsePythonVersion@0
          #   inputs:
          #     versionSpec: '$(pythonVersion)'
          #   displayName: 'Use Python version'

         # - task: AzureWebApp@1
          #  displayName: 'Deploy Azure Web App : Relecloud'
           # inputs:
            #  resourceGroupName: django
             # slotName: production
              #appType: webApp
              #azureSubscription: $(azureServiceConnectionId)
              #appName: $(webAppName)
              #package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip

              - task: AzureRmWebAppDeployment@5
                inputs:
                  ConnectionType: 'AzureRM'
                  azureSubscription: 'Azure for Students(033e26f8-876d-4414-b6bc-673accd6b842)'
                  appType: 'webAppLinux'
                  WebAppName: 'Relecloud-2526'
                  packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
                  DeploymentTypeLinux: 'oneDeploy'


