trigger:
- main

variables:
  azureServiceConnection: 'Azure for Students(033e26f8-876d-4414-b6bc-673accd6b842)'
  webAppName: 'Relecloud-2526'
  environmentName: 'Relecloud-2526'

  # Carpeta donde est√°n manage.py, relecloud/, project/, requirements.txt
  projectRoot: '$(Build.SourcesDirectory)\django\django'


stages:
# =========================
# BUILD
# =========================
- stage: Build
  displayName: 'Build stage'
  jobs:
  - job: BuildJob
    pool:
      name: 'IS2-Practica2'
    steps:
    - script: |
        echo Carpeta actual:
        cd
        dir
      displayName: 'Check working dir'
      

    - script: |
        echo Creando entorno virtual...
        python -m venv antenv

        echo Activando entorno virtual...
        call antenv\Scripts\activate

        echo Actualizando pip y setuptools...
        python -m pip install --upgrade pip
        pip install --upgrade setuptools

        echo Instalando dependencias desde requirements.txt...
        pip install -r requirements.txt
      workingDirectory: '$(projectRoot)'
      displayName: 'Install requirements'
      

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(projectRoot)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
        replaceExistingArchive: true

    - upload: '$(Build.ArtifactStagingDirectory)/app.zip'
      displayName: 'Upload package'
      artifact: drop


# =========================
# DEPLOY
# =========================
- stage: Deploy
  displayName: 'Deploy Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    pool: 
      name: 'IS2-Practica2'
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            displayName: 'Download build artifact'
            inputs:
              artifact: drop
              path: '$(Pipeline.Workspace)/drop'

          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App : Relecloud-2526'
            inputs:
              appType: webAppLinux
              azureSubscription: '$(azureServiceConnection)'
              appName: '$(webAppName)'
              package: '$(Pipeline.Workspace)/drop/app.zip'
