trigger:
- main

variables:
  # Service connection de esta organización (NOMBRE, tal como aparece en DevOps)
  azureServiceConnectionId: 'Azure for Students(033e26f8-876d-4414-b6bc-673accd6b842)'

  # Nombre de la Web App en Azure (puede ser el slot)
  webAppName: 'Relecloud-2526-g8hubyh8c4f9hcgz'
  # Si quieres la app base:
  # webAppName: 'Relecloud-2526'

  environmentName: 'Relecloud-2526'

  # Carpeta donde están manage.py, project/, relecloud/, requirements.txt
  projectRoot: '$(Build.SourcesDirectory)\django\django'

  pythonExe: 'python'


stages:
# ========== BUILD ==========
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool:
      name: 'IS2-Practica2'
    steps:
    - script: |
        echo Carpeta de trabajo:
        cd
        dir
      displayName: 'Check working dir'

    - script: |
        echo Creando entorno virtual...
        python -m venv antenv

        echo Activando entorno virtual...
        call antenv\Scripts\activate

        echo Actualizando pip...
        python -m pip install --upgrade pip

        echo Instalando dependencias...
        pip install -r requirements.txt
      workingDirectory: $(projectRoot)
      displayName: "Install requirements"

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(projectRoot)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    - upload: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      displayName: 'Upload package'
      artifact: drop


# ========== DEPLOY ==========
- stage: Deploy
  displayName: 'Deploy Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    pool:
      name: 'IS2-Practica2'
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            displayName: 'Download build artifact'
            inputs:
              artifact: drop
              path: '$(Pipeline.Workspace)/drop'

          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App : $(webAppName)'
            inputs:
              appType: webAppLinux
              azureSubscription: $(azureServiceConnectionId)
              appName: $(webAppName)
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
