trigger:
- main

variables:
  azureServiceConnectionId: 'abaa671b-36dd-4136-b05d-ecfb61eaf3c1'
  webAppName: 'Relecloud-2526'
  environmentName: 'Relecloud-2526'
  projectRoot: $(System.DefaultWorkingDirectory)

stages:
- stage: Build
  displayName: 'Build stage'
  jobs:
  - job: BuildJob
    displayName: 'BuildJob'
    pool:
      name: 'IS2-Practica2'   # ← pon aquí el pool donde está tu agente
    steps:
    - script: |
        python --version
      displayName: 'Check Python version'
      

    - script: |
        python -m venv antenv
        call antenv\Scripts\activate
        python -m pip install --upgrade pip
        pip install setuptools
        pip install -r requirements.txt
      workingDirectory: $(projectRoot)
      displayName: 'Install requirements'
      

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(projectRoot)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    - upload: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      displayName: 'Upload package'
      artifact: drop

- stage: Deploy
  displayName: 'Deploy Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    displayName: 'DeploymentJob'
    pool:
      name: 'IS2-Practica2'   # mismo pool/PC
    environment: $(environmentName)
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App : Relecloud-2526'
            inputs:
              appType: webApp
              azureSubscription: 
              appName: $(webAppName)
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
